jrhurley2/TDInterface-Public

TdInterface/MainForm.cs, TdInterface/TdHelper.cs
Added Dictionary to keep track of placed orders
Update ConsumerKey calls. to not be hardcoded.
=> Altered Place Order to get the orderKey from the location Uri.

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/OrderHelper.cs, TdInterface/TdHelper.cs, TdInterfaceTests/OrderHelperTests.cs
REfator OCO orders to use generic routines.
=> Cleanup oco orders

TdInterface/MainForm.cs, TdInterface/Model/OrderFillMessage.cs, TdInterface/TDStreamer.cs, TdInterfaceTests/TDStreamerTests.cs
Changed TDStreamer to not parse the xml for Order fill and Order Recieved, was not using anyway and I do not have a complete xml schema.
Added Logging and enabled Replay file.
=> Added some new fields to orderfillmessage

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/TdHelper.cs
Added a cancel all button with a hotkey of Ctrl+A
=> Added Cancel All Button

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/Settings.cs, TdInterface/UserOptionsForm.Designer.cs, TdInterface/UserOptionsForm.cs, TdInterface/Utility.cs
Updated Cancel All to call out and get all the orders at cancel time.  Keeping track was not working correctly.
=> Added Options page

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs
Fixed problem with Cancel All where PENDING_ACTIVATION wasn't being closed.
=> Add close on bid ask

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterfaceTests/OrderHelperTests.cs
Moved screen around a little
Fixed unit tests.
=> Add Text Box for setting stop.

TdInterface/MainForm.cs
On leave of txtSymbol field clear the stop, limit and stoptoclose fields
=> Clear stop, limit and stoptoclose when symbol changes

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs
Added as limit offset text box.
Changed behavior of Limit to  open buttons, not if limit is blank and offset is filled in, it will create a maketable limit order with the limit being bid/ask +offset.  All oco calculations will be based off this limit value.
=> Added Limit offset text box.

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/Settings.cs, TdInterface/UserOptionsForm.Designer.cs, TdInterface/UserOptionsForm.cs
Updated the 1st target percentage to be configurable from the settings screen.
=> Adjustable1 r size

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs
=> Added Risk/Reward Textbox to track How many R

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/TdHelper.cs
Changed PriceHistory to get by 1 min for current day.
Zeroed out the R Value when changing position closed.
=> Minor Bug Fixes

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/MasterForm.Designer.cs, TdInterface/MasterForm.cs, TdInterface/Settings.cs, TdInterface/UserOptionsForm.Designer.cs, TdInterface/UserOptionsForm.cs
Cleaning up of the forms from the dictionary.
Created Named Forms based on Ticker symbol
Created DefaultLimitOffset
=> Random enhancements

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/MainForm.resx, TdInterface/Model/SecuritiesAccount.cs, TdInterface/Settings.cs, TdInterface/TdHelper.cs, TdInterface/UserOptionsForm.Designer.cs, TdInterface/UserOptionsForm.cs
Added MaxLossLimit in R to options screen (this is not yet functional) 
Gave the OneRPRofitPrecentage a default of 25%
Added Debug Statement to spit out the Account Info to the .log. 
Added Debug statement to spit out the order
Added PnL calc to SecuritiesAccount
Added Min Risk for calculation of Open Shares.
Addded code to attempt to create stop after 1st Limit Order filled.
=> Added Minimum Risk to the options screen

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/MainForm.resx
Added check in GenericOco to check to see if daily limit has been hit.  Don't proceed with order if it is.
=> Added timer to refresh securities account

TdInterface/MainForm.Designer.cs, TdInterface/MainForm.cs, TdInterface/Settings.cs, TdInterface/UserOptionsForm.Designer.cs, TdInterface/UserOptionsForm.cs
Added missing check to see if enabled to max loss check
Made PnL an option
=> Added missing check to see if enabled to max loss check

TdInterface/Forms/MainForm.Designer.cs
Made the one to one even bigger as it wasn't showing up correctly on a mac.
=> made one to one even bigger

TdInterface/Forms/MainForm.cs, TdInterface/Forms/MasterForm.cs, TdInterface/Forms/UserOptionsForm.Designer.cs, TdInterface/TdInterface.csproj, TdInterface/Tda/TDStreamer.cs
Minor cleanup to remove code causing warnings, and moved replays/logs to their own folders to clean up the directory.
=> Minor code cleanup

TdInterface/Forms/MainForm.Designer.cs, TdInterface/Forms/MainForm.cs, TdInterface/Forms/MasterForm.Designer.cs, TdInterface/Forms/MasterForm.cs, TdInterface/Forms/UserOptionsForm.Designer.cs, TdInterface/Forms/UserOptionsForm.cs, TdInterface/Settings.cs, TdInterface/TradeStation/TradeStationStreamer.cs, TdInterface/Utility.cs
Adding support to capture screenshots on trade open using native C# instead of a 3rd party application.
Also fixed check to send print screen commands (for Snag) only when settings are on to do so.
=> Native screen capture support

TdInterface/TdInterface.csproj
Removed ProKn1fe webview runtime and replaced with Microsoft provided WebView to majorly reduce file and memory footprint of app
=> Swapping simple webview for master / current release.

TdInterface/Forms/MainForm.Designer.cs
Fix #90 to enable trade window to be minimized.
=> Enable minimize button on trade form.

.github/workflows/dotnet.yml, TdInterface/Forms/MainForm.cs, TdInterface/TdInterface.csproj, TdInterfaceTests/MainFormTests.cs, TdInterfaceTests/Tda/TDAOrderHelperTests.cs
=> 96 increment version number

TdInterface/Forms/MainForm.Designer.cs, TdInterface/Forms/MainForm.cs
Quickly added version number to the trading/main form, can add it to others if we need it, but starting with it here for now.
Fixes #91
=> Adding Version # to App

TdInterface/Forms/MainForm.Designer.cs, TdInterface/Forms/MainForm.cs, TdInterface/Forms/UserOptionsForm.Designer.cs, TdInterface/Forms/UserOptionsForm.cs, TdInterface/Tda/TDAOrderHelper.cs
Moved CalcShares to TDATradeHelper for now. Given we share this for both TDA and TS, this seems OK for now. When we do refactor to have interfaces for TDA/TS to share, we can have this be part of the base class.
Also renamed training wheels to tradeShares and fixed a style bug between us with the prefix for checkboxes. I use cb, you have used chk elsewhere - works for me, as cb would probably be better for combobox anyways :)
=> CalcShares Refactor

TdInterface/TradeStation/Model/StockQuote.cs, TdInterface/TradeStation/TradeStationHelper.cs
Fix TS Stockqoute  needed setters when updating.
=> Added setters to the TS stockquote as it was failing to Update()

TdInterface/Forms/MainForm.Designer.cs, TdInterface/Forms/MainForm.cs, TdInterface/Tda/TDAOrderHelper.cs
Toggling enabled/disabled state of buttons based on position.
=> Toggle button states
